services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    restart: always
    ports:
      - 8545:8545
    networks:
      - dapp-web
  provider:
    image: olelarsen/provider
    container_name: provider
    environment:
      PORT: 5555
    ports:
      - 5555:5555
    networks:
      - dapp-web
    restart: always
networks:
  dapp-web:
    name: dapp-web
    driver: bridge