// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendAuthWalletConnectHandlerFunc turns a function with the right signature into a get frontend auth wallet connect handler
type GetFrontendAuthWalletConnectHandlerFunc func(GetFrontendAuthWalletConnectParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendAuthWalletConnectHandlerFunc) Handle(params GetFrontendAuthWalletConnectParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendAuthWalletConnectHandler interface for that can handle valid get frontend auth wallet connect params
type GetFrontendAuthWalletConnectHandler interface {
	Handle(GetFrontendAuthWalletConnectParams, *models.Principal) middleware.Responder
}

// NewGetFrontendAuthWalletConnect creates a new http.Handler for the get frontend auth wallet connect operation
func NewGetFrontendAuthWalletConnect(ctx *middleware.Context, handler GetFrontendAuthWalletConnectHandler) *GetFrontendAuthWalletConnect {
	return &GetFrontendAuthWalletConnect{Context: ctx, Handler: handler}
}

/*
	GetFrontendAuthWalletConnect swagger:route GET /frontend/auth/wallet-connect auth getFrontendAuthWalletConnect

This API endpoint create, store and returns credentials for new user
*/
type GetFrontendAuthWalletConnect struct {
	Context *middleware.Context
	Handler GetFrontendAuthWalletConnectHandler
}

func (o *GetFrontendAuthWalletConnect) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendAuthWalletConnectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
