// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFrontendAuthCallbackHandlerFunc turns a function with the right signature into a get frontend auth callback handler
type GetFrontendAuthCallbackHandlerFunc func(GetFrontendAuthCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendAuthCallbackHandlerFunc) Handle(params GetFrontendAuthCallbackParams) middleware.Responder {
	return fn(params)
}

// GetFrontendAuthCallbackHandler interface for that can handle valid get frontend auth callback params
type GetFrontendAuthCallbackHandler interface {
	Handle(GetFrontendAuthCallbackParams) middleware.Responder
}

// NewGetFrontendAuthCallback creates a new http.Handler for the get frontend auth callback operation
func NewGetFrontendAuthCallback(ctx *middleware.Context, handler GetFrontendAuthCallbackHandler) *GetFrontendAuthCallback {
	return &GetFrontendAuthCallback{Context: ctx, Handler: handler}
}

/*
	GetFrontendAuthCallback swagger:route GET /frontend/auth/callback Auth getFrontendAuthCallback

oauth2 callback from provider
*/
type GetFrontendAuthCallback struct {
	Context *middleware.Context
	Handler GetFrontendAuthCallbackHandler
}

func (o *GetFrontendAuthCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendAuthCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
