// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Plutonium Service API
//
//	The Plutonium Service API provides endpoints to support the operations of the NFT Marketplace.
//	This document outlines the API's structure, response formats, and capabilities for integration.
//
//	Schemes:
//	  http
//	Host: plutonium
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
