swagger: "2.0"
info:
  description: "This API provides access to the Plutonium Frontend, which allows interaction with the system's public data."
  title: "Plutonium Frontend API"
  version: "1.0.0"
host: "plutonium"
basePath: "/api/v1"
schemes:
  - http
securityDefinitions:
  bearer:
    type: apiKey
    in: header
    name: Authorization
    description: "Bearer token used for authentication. Example: 'Bearer <token>'"
  x-token:
    type: apiKey
    in: header
    name: x-token
    description: "Custom token used for accessing public endpoints."
paths:
  /header:
    get:
      security:
        - x-token: []
      tags:
        - public
      parameters:
        - name: provider
          in: query
          type: string
          description: "The provider to be used in the header"
          required: false
      summary: "Fetches the public header for the frontend."
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully fetched the header."
          schema:
            $ref: "#/definitions/PublicHeaderResponse"
        400:
          description: "Bad request due to missing or invalid parameters."
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "Unauthorized. The request is missing valid authentication."
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Not found. The requested resource could not be found."
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  principal:
    type: string
    description: "A unique identifier for a principal (user or entity)."
  ErrorResponse:
    type: object
    properties:
      code:
        type: integer
        example: 500
        description: "HTTP status code representing the error encountered."
      message:
        type: string
        example: "Internal Server Error"
        description: "A brief explanation of the error."
      details:
        type: string
        example: "Unexpected error while processing the request."
        description: "Additional context about the error, if available."
  PublicHeaderResponse:
    type: object
    properties:
      menu:
        $ref: "#/definitions/PublicMenu"
    description: "Represents the public header information, including menu items."
  PublicMenu:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: "Unique identifier for the menu item."
      attributes:
        type: object
        $ref: '#/definitions/PublicMenuAttributes'
    description: "Represents a menu item in the public header."
  PublicMenuAttributes:
    type: object
    properties:
      orderBy:
        type: integer
        format: int64
        description: "Order of the menu item in the list."
      name:
        type: string
        description: "Name of the menu item."
      link:
        type: string
        description: "URL link for the menu item."
      items:
        type: array
        items:
          $ref: "#/definitions/PublicMenu"
        description: "Submenu items, if any."
  tags:
    - description: "API V1 request"
      name: v1
    - description: "Public endpoints for frontend interaction"
      name: public
