// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendContactHandlerFunc turns a function with the right signature into a get frontend contact handler
type GetFrontendContactHandlerFunc func(GetFrontendContactParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendContactHandlerFunc) Handle(params GetFrontendContactParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendContactHandler interface for that can handle valid get frontend contact params
type GetFrontendContactHandler interface {
	Handle(GetFrontendContactParams, *models.Principal) middleware.Responder
}

// NewGetFrontendContact creates a new http.Handler for the get frontend contact operation
func NewGetFrontendContact(ctx *middleware.Context, handler GetFrontendContactHandler) *GetFrontendContact {
	return &GetFrontendContact{Context: ctx, Handler: handler}
}

/*
	GetFrontendContact swagger:route GET /frontend/contact Frontend getFrontendContact

get contact form for page contact
*/
type GetFrontendContact struct {
	Context *middleware.Context
	Handler GetFrontendContactHandler
}

func (o *GetFrontendContact) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendContactParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
