// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendContactOKCode is the HTTP code returned for type GetFrontendContactOK
const GetFrontendContactOKCode int = 200

/*
GetFrontendContactOK ok

swagger:response getFrontendContactOK
*/
type GetFrontendContactOK struct {

	/*
	  In: Body
	*/
	Payload *models.PublicContact `json:"body,omitempty"`
}

// NewGetFrontendContactOK creates GetFrontendContactOK with default headers values
func NewGetFrontendContactOK() *GetFrontendContactOK {

	return &GetFrontendContactOK{}
}

// WithPayload adds the payload to the get frontend contact o k response
func (o *GetFrontendContactOK) WithPayload(payload *models.PublicContact) *GetFrontendContactOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend contact o k response
func (o *GetFrontendContactOK) SetPayload(payload *models.PublicContact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendContactOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendContactBadRequestCode is the HTTP code returned for type GetFrontendContactBadRequest
const GetFrontendContactBadRequestCode int = 400

/*
GetFrontendContactBadRequest Bad request due to missing or invalid parameters.

swagger:response getFrontendContactBadRequest
*/
type GetFrontendContactBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendContactBadRequest creates GetFrontendContactBadRequest with default headers values
func NewGetFrontendContactBadRequest() *GetFrontendContactBadRequest {

	return &GetFrontendContactBadRequest{}
}

// WithPayload adds the payload to the get frontend contact bad request response
func (o *GetFrontendContactBadRequest) WithPayload(payload *models.ErrorResponse) *GetFrontendContactBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend contact bad request response
func (o *GetFrontendContactBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendContactBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendContactUnauthorizedCode is the HTTP code returned for type GetFrontendContactUnauthorized
const GetFrontendContactUnauthorizedCode int = 401

/*
GetFrontendContactUnauthorized Unauthorized. The request is missing valid authentication.

swagger:response getFrontendContactUnauthorized
*/
type GetFrontendContactUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendContactUnauthorized creates GetFrontendContactUnauthorized with default headers values
func NewGetFrontendContactUnauthorized() *GetFrontendContactUnauthorized {

	return &GetFrontendContactUnauthorized{}
}

// WithPayload adds the payload to the get frontend contact unauthorized response
func (o *GetFrontendContactUnauthorized) WithPayload(payload *models.ErrorResponse) *GetFrontendContactUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend contact unauthorized response
func (o *GetFrontendContactUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendContactUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendContactNotFoundCode is the HTTP code returned for type GetFrontendContactNotFound
const GetFrontendContactNotFoundCode int = 404

/*
GetFrontendContactNotFound Not found. The requested resource could not be found.

swagger:response getFrontendContactNotFound
*/
type GetFrontendContactNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendContactNotFound creates GetFrontendContactNotFound with default headers values
func NewGetFrontendContactNotFound() *GetFrontendContactNotFound {

	return &GetFrontendContactNotFound{}
}

// WithPayload adds the payload to the get frontend contact not found response
func (o *GetFrontendContactNotFound) WithPayload(payload *models.ErrorResponse) *GetFrontendContactNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend contact not found response
func (o *GetFrontendContactNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendContactNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendContactInternalServerErrorCode is the HTTP code returned for type GetFrontendContactInternalServerError
const GetFrontendContactInternalServerErrorCode int = 500

/*
GetFrontendContactInternalServerError Internal server error.

swagger:response getFrontendContactInternalServerError
*/
type GetFrontendContactInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendContactInternalServerError creates GetFrontendContactInternalServerError with default headers values
func NewGetFrontendContactInternalServerError() *GetFrontendContactInternalServerError {

	return &GetFrontendContactInternalServerError{}
}

// WithPayload adds the payload to the get frontend contact internal server error response
func (o *GetFrontendContactInternalServerError) WithPayload(payload *models.ErrorResponse) *GetFrontendContactInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend contact internal server error response
func (o *GetFrontendContactInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendContactInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
