// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendPageSlugHandlerFunc turns a function with the right signature into a get frontend page slug handler
type GetFrontendPageSlugHandlerFunc func(GetFrontendPageSlugParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendPageSlugHandlerFunc) Handle(params GetFrontendPageSlugParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendPageSlugHandler interface for that can handle valid get frontend page slug params
type GetFrontendPageSlugHandler interface {
	Handle(GetFrontendPageSlugParams, *models.Principal) middleware.Responder
}

// NewGetFrontendPageSlug creates a new http.Handler for the get frontend page slug operation
func NewGetFrontendPageSlug(ctx *middleware.Context, handler GetFrontendPageSlugHandler) *GetFrontendPageSlug {
	return &GetFrontendPageSlug{Context: ctx, Handler: handler}
}

/*
	GetFrontendPageSlug swagger:route GET /frontend/page/:slug Frontend getFrontendPageSlug

page
*/
type GetFrontendPageSlug struct {
	Context *middleware.Context
	Handler GetFrontendPageSlugHandler
}

func (o *GetFrontendPageSlug) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendPageSlugParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
