// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendFooterOKCode is the HTTP code returned for type GetFrontendFooterOK
const GetFrontendFooterOKCode int = 200

/*
GetFrontendFooterOK Successfully fetched the footer.

swagger:response getFrontendFooterOK
*/
type GetFrontendFooterOK struct {

	/*
	  In: Body
	*/
	Payload *models.PublicFooterResponse `json:"body,omitempty"`
}

// NewGetFrontendFooterOK creates GetFrontendFooterOK with default headers values
func NewGetFrontendFooterOK() *GetFrontendFooterOK {

	return &GetFrontendFooterOK{}
}

// WithPayload adds the payload to the get frontend footer o k response
func (o *GetFrontendFooterOK) WithPayload(payload *models.PublicFooterResponse) *GetFrontendFooterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend footer o k response
func (o *GetFrontendFooterOK) SetPayload(payload *models.PublicFooterResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendFooterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendFooterBadRequestCode is the HTTP code returned for type GetFrontendFooterBadRequest
const GetFrontendFooterBadRequestCode int = 400

/*
GetFrontendFooterBadRequest Bad request due to missing or invalid parameters.

swagger:response getFrontendFooterBadRequest
*/
type GetFrontendFooterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendFooterBadRequest creates GetFrontendFooterBadRequest with default headers values
func NewGetFrontendFooterBadRequest() *GetFrontendFooterBadRequest {

	return &GetFrontendFooterBadRequest{}
}

// WithPayload adds the payload to the get frontend footer bad request response
func (o *GetFrontendFooterBadRequest) WithPayload(payload *models.ErrorResponse) *GetFrontendFooterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend footer bad request response
func (o *GetFrontendFooterBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendFooterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendFooterUnauthorizedCode is the HTTP code returned for type GetFrontendFooterUnauthorized
const GetFrontendFooterUnauthorizedCode int = 401

/*
GetFrontendFooterUnauthorized Unauthorized. The request is missing valid authentication.

swagger:response getFrontendFooterUnauthorized
*/
type GetFrontendFooterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendFooterUnauthorized creates GetFrontendFooterUnauthorized with default headers values
func NewGetFrontendFooterUnauthorized() *GetFrontendFooterUnauthorized {

	return &GetFrontendFooterUnauthorized{}
}

// WithPayload adds the payload to the get frontend footer unauthorized response
func (o *GetFrontendFooterUnauthorized) WithPayload(payload *models.ErrorResponse) *GetFrontendFooterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend footer unauthorized response
func (o *GetFrontendFooterUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendFooterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendFooterNotFoundCode is the HTTP code returned for type GetFrontendFooterNotFound
const GetFrontendFooterNotFoundCode int = 404

/*
GetFrontendFooterNotFound Not found. The requested resource could not be found.

swagger:response getFrontendFooterNotFound
*/
type GetFrontendFooterNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendFooterNotFound creates GetFrontendFooterNotFound with default headers values
func NewGetFrontendFooterNotFound() *GetFrontendFooterNotFound {

	return &GetFrontendFooterNotFound{}
}

// WithPayload adds the payload to the get frontend footer not found response
func (o *GetFrontendFooterNotFound) WithPayload(payload *models.ErrorResponse) *GetFrontendFooterNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend footer not found response
func (o *GetFrontendFooterNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendFooterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFrontendFooterInternalServerErrorCode is the HTTP code returned for type GetFrontendFooterInternalServerError
const GetFrontendFooterInternalServerErrorCode int = 500

/*
GetFrontendFooterInternalServerError Internal server error.

swagger:response getFrontendFooterInternalServerError
*/
type GetFrontendFooterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetFrontendFooterInternalServerError creates GetFrontendFooterInternalServerError with default headers values
func NewGetFrontendFooterInternalServerError() *GetFrontendFooterInternalServerError {

	return &GetFrontendFooterInternalServerError{}
}

// WithPayload adds the payload to the get frontend footer internal server error response
func (o *GetFrontendFooterInternalServerError) WithPayload(payload *models.ErrorResponse) *GetFrontendFooterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frontend footer internal server error response
func (o *GetFrontendFooterInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrontendFooterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
