// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendCategoriesHandlerFunc turns a function with the right signature into a get frontend categories handler
type GetFrontendCategoriesHandlerFunc func(GetFrontendCategoriesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendCategoriesHandlerFunc) Handle(params GetFrontendCategoriesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendCategoriesHandler interface for that can handle valid get frontend categories params
type GetFrontendCategoriesHandler interface {
	Handle(GetFrontendCategoriesParams, *models.Principal) middleware.Responder
}

// NewGetFrontendCategories creates a new http.Handler for the get frontend categories operation
func NewGetFrontendCategories(ctx *middleware.Context, handler GetFrontendCategoriesHandler) *GetFrontendCategories {
	return &GetFrontendCategories{Context: ctx, Handler: handler}
}

/*
	GetFrontendCategories swagger:route GET /frontend/categories Frontend getFrontendCategories

get market data categories
*/
type GetFrontendCategories struct {
	Context *middleware.Context
	Handler GetFrontendCategoriesHandler
}

func (o *GetFrontendCategories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendCategoriesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
