// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendMenuHandlerFunc turns a function with the right signature into a get frontend menu handler
type GetFrontendMenuHandlerFunc func(GetFrontendMenuParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendMenuHandlerFunc) Handle(params GetFrontendMenuParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendMenuHandler interface for that can handle valid get frontend menu params
type GetFrontendMenuHandler interface {
	Handle(GetFrontendMenuParams, *models.Principal) middleware.Responder
}

// NewGetFrontendMenu creates a new http.Handler for the get frontend menu operation
func NewGetFrontendMenu(ctx *middleware.Context, handler GetFrontendMenuHandler) *GetFrontendMenu {
	return &GetFrontendMenu{Context: ctx, Handler: handler}
}

/*
	GetFrontendMenu swagger:route GET /frontend/menu Frontend getFrontendMenu

Fetches the public menu for the frontend.
*/
type GetFrontendMenu struct {
	Context *middleware.Context
	Handler GetFrontendMenuHandler
}

func (o *GetFrontendMenu) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendMenuParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
