// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendUsersHandlerFunc turns a function with the right signature into a get frontend users handler
type GetFrontendUsersHandlerFunc func(GetFrontendUsersParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendUsersHandlerFunc) Handle(params GetFrontendUsersParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendUsersHandler interface for that can handle valid get frontend users params
type GetFrontendUsersHandler interface {
	Handle(GetFrontendUsersParams, *models.Principal) middleware.Responder
}

// NewGetFrontendUsers creates a new http.Handler for the get frontend users operation
func NewGetFrontendUsers(ctx *middleware.Context, handler GetFrontendUsersHandler) *GetFrontendUsers {
	return &GetFrontendUsers{Context: ctx, Handler: handler}
}

/*
	GetFrontendUsers swagger:route GET /frontend/users Frontend getFrontendUsers

this route fetch public users who has address
*/
type GetFrontendUsers struct {
	Context *middleware.Context
	Handler GetFrontendUsersHandler
}

func (o *GetFrontendUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendUsersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
