// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/plutonium/models"
)

// PostFrontendContactFormOKCode is the HTTP code returned for type PostFrontendContactFormOK
const PostFrontendContactFormOKCode int = 200

/*
PostFrontendContactFormOK successful create

swagger:response postFrontendContactFormOK
*/
type PostFrontendContactFormOK struct {

	/*
	  In: Body
	*/
	Payload *models.FormSuccess `json:"body,omitempty"`
}

// NewPostFrontendContactFormOK creates PostFrontendContactFormOK with default headers values
func NewPostFrontendContactFormOK() *PostFrontendContactFormOK {

	return &PostFrontendContactFormOK{}
}

// WithPayload adds the payload to the post frontend contact form o k response
func (o *PostFrontendContactFormOK) WithPayload(payload *models.FormSuccess) *PostFrontendContactFormOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post frontend contact form o k response
func (o *PostFrontendContactFormOK) SetPayload(payload *models.FormSuccess) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFrontendContactFormOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFrontendContactFormBadRequestCode is the HTTP code returned for type PostFrontendContactFormBadRequest
const PostFrontendContactFormBadRequestCode int = 400

/*
PostFrontendContactFormBadRequest Bad request due to missing or invalid parameters.

swagger:response postFrontendContactFormBadRequest
*/
type PostFrontendContactFormBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFrontendContactFormBadRequest creates PostFrontendContactFormBadRequest with default headers values
func NewPostFrontendContactFormBadRequest() *PostFrontendContactFormBadRequest {

	return &PostFrontendContactFormBadRequest{}
}

// WithPayload adds the payload to the post frontend contact form bad request response
func (o *PostFrontendContactFormBadRequest) WithPayload(payload *models.ErrorResponse) *PostFrontendContactFormBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post frontend contact form bad request response
func (o *PostFrontendContactFormBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFrontendContactFormBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFrontendContactFormUnauthorizedCode is the HTTP code returned for type PostFrontendContactFormUnauthorized
const PostFrontendContactFormUnauthorizedCode int = 401

/*
PostFrontendContactFormUnauthorized Unauthorized. The request is missing valid authentication.

swagger:response postFrontendContactFormUnauthorized
*/
type PostFrontendContactFormUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFrontendContactFormUnauthorized creates PostFrontendContactFormUnauthorized with default headers values
func NewPostFrontendContactFormUnauthorized() *PostFrontendContactFormUnauthorized {

	return &PostFrontendContactFormUnauthorized{}
}

// WithPayload adds the payload to the post frontend contact form unauthorized response
func (o *PostFrontendContactFormUnauthorized) WithPayload(payload *models.ErrorResponse) *PostFrontendContactFormUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post frontend contact form unauthorized response
func (o *PostFrontendContactFormUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFrontendContactFormUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFrontendContactFormNotFoundCode is the HTTP code returned for type PostFrontendContactFormNotFound
const PostFrontendContactFormNotFoundCode int = 404

/*
PostFrontendContactFormNotFound Not found. The requested resource could not be found.

swagger:response postFrontendContactFormNotFound
*/
type PostFrontendContactFormNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFrontendContactFormNotFound creates PostFrontendContactFormNotFound with default headers values
func NewPostFrontendContactFormNotFound() *PostFrontendContactFormNotFound {

	return &PostFrontendContactFormNotFound{}
}

// WithPayload adds the payload to the post frontend contact form not found response
func (o *PostFrontendContactFormNotFound) WithPayload(payload *models.ErrorResponse) *PostFrontendContactFormNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post frontend contact form not found response
func (o *PostFrontendContactFormNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFrontendContactFormNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFrontendContactFormInternalServerErrorCode is the HTTP code returned for type PostFrontendContactFormInternalServerError
const PostFrontendContactFormInternalServerErrorCode int = 500

/*
PostFrontendContactFormInternalServerError Internal server error.

swagger:response postFrontendContactFormInternalServerError
*/
type PostFrontendContactFormInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFrontendContactFormInternalServerError creates PostFrontendContactFormInternalServerError with default headers values
func NewPostFrontendContactFormInternalServerError() *PostFrontendContactFormInternalServerError {

	return &PostFrontendContactFormInternalServerError{}
}

// WithPayload adds the payload to the post frontend contact form internal server error response
func (o *PostFrontendContactFormInternalServerError) WithPayload(payload *models.ErrorResponse) *PostFrontendContactFormInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post frontend contact form internal server error response
func (o *PostFrontendContactFormInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFrontendContactFormInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
