// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostFrontendContactFormHandlerFunc turns a function with the right signature into a post frontend contact form handler
type PostFrontendContactFormHandlerFunc func(PostFrontendContactFormParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFrontendContactFormHandlerFunc) Handle(params PostFrontendContactFormParams) middleware.Responder {
	return fn(params)
}

// PostFrontendContactFormHandler interface for that can handle valid post frontend contact form params
type PostFrontendContactFormHandler interface {
	Handle(PostFrontendContactFormParams) middleware.Responder
}

// NewPostFrontendContactForm creates a new http.Handler for the post frontend contact form operation
func NewPostFrontendContactForm(ctx *middleware.Context, handler PostFrontendContactFormHandler) *PostFrontendContactForm {
	return &PostFrontendContactForm{Context: ctx, Handler: handler}
}

/*
	PostFrontendContactForm swagger:route POST /frontend/contact-form Frontend postFrontendContactForm

Send contact form.
*/
type PostFrontendContactForm struct {
	Context *middleware.Context
	Handler PostFrontendContactFormHandler
}

func (o *PostFrontendContactForm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostFrontendContactFormParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
