// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/plutonium/models"
)

// GetFrontendHelpCenterHandlerFunc turns a function with the right signature into a get frontend help center handler
type GetFrontendHelpCenterHandlerFunc func(GetFrontendHelpCenterParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontendHelpCenterHandlerFunc) Handle(params GetFrontendHelpCenterParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFrontendHelpCenterHandler interface for that can handle valid get frontend help center params
type GetFrontendHelpCenterHandler interface {
	Handle(GetFrontendHelpCenterParams, *models.Principal) middleware.Responder
}

// NewGetFrontendHelpCenter creates a new http.Handler for the get frontend help center operation
func NewGetFrontendHelpCenter(ctx *middleware.Context, handler GetFrontendHelpCenterHandler) *GetFrontendHelpCenter {
	return &GetFrontendHelpCenter{Context: ctx, Handler: handler}
}

/*
	GetFrontendHelpCenter swagger:route GET /frontend/help-center public getFrontendHelpCenter

help center
*/
type GetFrontendHelpCenter struct {
	Context *middleware.Context
	Handler GetFrontendHelpCenterHandler
}

func (o *GetFrontendHelpCenter) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontendHelpCenterParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
