// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Author author
//
// swagger:model Author
type Author struct {

	// created
	// Format: date
	Created strfmt.Date `json:"created,omitempty"`

	// created by id
	CreatedByID int64 `json:"created_by_id,omitempty"`

	// deleted
	// Format: date
	Deleted strfmt.Date `json:"deleted,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// image id
	ImageID int64 `json:"image_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// order by
	OrderBy int64 `json:"order_by,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// socials
	Socials []*Social `json:"socials"`

	// title
	Title string `json:"title,omitempty"`

	// updated
	// Format: date
	Updated strfmt.Date `json:"updated,omitempty"`

	// updated by id
	UpdatedByID int64 `json:"updated_by_id,omitempty"`

	// wallets
	Wallets []*Wallet `json:"wallets"`
}

// Validate validates this author
func (m *Author) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSocials(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWallets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Author) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Author) validateDeleted(formats strfmt.Registry) error {
	if swag.IsZero(m.Deleted) { // not required
		return nil
	}

	if err := validate.FormatOf("deleted", "body", "date", m.Deleted.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Author) validateSocials(formats strfmt.Registry) error {
	if swag.IsZero(m.Socials) { // not required
		return nil
	}

	for i := 0; i < len(m.Socials); i++ {
		if swag.IsZero(m.Socials[i]) { // not required
			continue
		}

		if m.Socials[i] != nil {
			if err := m.Socials[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("socials" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("socials" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Author) validateUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if err := validate.FormatOf("updated", "body", "date", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Author) validateWallets(formats strfmt.Registry) error {
	if swag.IsZero(m.Wallets) { // not required
		return nil
	}

	for i := 0; i < len(m.Wallets); i++ {
		if swag.IsZero(m.Wallets[i]) { // not required
			continue
		}

		if m.Wallets[i] != nil {
			if err := m.Wallets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("wallets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("wallets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this author based on the context it is used
func (m *Author) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSocials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWallets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Author) contextValidateSocials(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Socials); i++ {

		if m.Socials[i] != nil {

			if swag.IsZero(m.Socials[i]) { // not required
				return nil
			}

			if err := m.Socials[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("socials" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("socials" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Author) contextValidateWallets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Wallets); i++ {

		if m.Wallets[i] != nil {

			if swag.IsZero(m.Wallets[i]) { // not required
				return nil
			}

			if err := m.Wallets[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("wallets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("wallets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Author) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Author) UnmarshalBinary(b []byte) error {
	var res Author
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
