// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FileResponse file response
//
// swagger:model FileResponse
type FileResponse string

// Validate validates this file response
func (m FileResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file response based on context it is used
func (m FileResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
