// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarketplaceCollectibleDetails marketplace collectible details
//
// swagger:model MarketplaceCollectibleDetails
type MarketplaceCollectibleDetails struct {

	// address
	Address string `json:"address,omitempty"`

	// auction
	Auction bool `json:"auction,omitempty"`

	// cancelled
	Cancelled bool `json:"cancelled,omitempty"`

	// collection
	Collection string `json:"collection,omitempty"`

	// end time
	EndTime int64 `json:"end_time,omitempty"`

	// fee
	Fee string `json:"fee,omitempty"`

	// fee wei
	FeeWei string `json:"fee_wei,omitempty"`

	// fulfilled
	Fulfilled bool `json:"fulfilled,omitempty"`

	// is started
	IsStarted bool `json:"is_started,omitempty"`

	// price
	Price string `json:"price,omitempty"`

	// price wei
	PriceWei string `json:"price_wei,omitempty"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`

	// reserve price
	ReservePrice string `json:"reserve_price,omitempty"`

	// reserve price wei
	ReservePriceWei string `json:"reserve_price_wei,omitempty"`

	// start price
	StartPrice string `json:"start_price,omitempty"`

	// start price wei
	StartPriceWei string `json:"start_price_wei,omitempty"`

	// start time
	StartTime int64 `json:"start_time,omitempty"`

	// tags
	Tags string `json:"tags,omitempty"`

	// total
	Total string `json:"total,omitempty"`

	// total wei
	TotalWei string `json:"total_wei,omitempty"`
}

// Validate validates this marketplace collectible details
func (m *MarketplaceCollectibleDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this marketplace collectible details based on context it is used
func (m *MarketplaceCollectibleDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarketplaceCollectibleDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarketplaceCollectibleDetails) UnmarshalBinary(b []byte) error {
	var res MarketplaceCollectibleDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
