// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PublicMarketplaceContract public marketplace contract
//
// swagger:model PublicMarketplaceContract
type PublicMarketplaceContract struct {

	// abi
	Abi string `json:"abi,omitempty"`

	// address
	Address string `json:"address,omitempty"`

	// fee
	Fee big.Int `json:"fee,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// owner
	Owner common.Address `json:"owner,omitempty"`
}

// Validate validates this public marketplace contract
func (m *PublicMarketplaceContract) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this public marketplace contract based on context it is used
func (m *PublicMarketplaceContract) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicMarketplaceContract) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicMarketplaceContract) UnmarshalBinary(b []byte) error {
	var res PublicMarketplaceContract
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
