// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PublicContactForm public contact form
//
// swagger:model PublicContactForm
type PublicContactForm struct {

	// csrf
	Csrf string `json:"csrf,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// page Id
	PageID int64 `json:"pageId,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this public contact form
func (m *PublicContactForm) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this public contact form based on context it is used
func (m *PublicContactForm) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicContactForm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicContactForm) UnmarshalBinary(b []byte) error {
	var res PublicContactForm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
