// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PublicFaqItemAttributes public faq item attributes
//
// swagger:model PublicFaqItemAttributes
type PublicFaqItemAttributes struct {

	// answer
	Answer string `json:"answer,omitempty"`

	// question
	Question string `json:"question,omitempty"`
}

// Validate validates this public faq item attributes
func (m *PublicFaqItemAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this public faq item attributes based on context it is used
func (m *PublicFaqItemAttributes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublicFaqItemAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicFaqItemAttributes) UnmarshalBinary(b []byte) error {
	var res PublicFaqItemAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
